#!/bin/bash
#SBATCH -A cgb              # Account name (adjust as needed)
#SBATCH -p ai               # Partition
#SBATCH -q preemptible      # Queue
#SBATCH --nodes=1           # Number of nodes
#SBATCH --ntasks=1          # Number of tasks
#SBATCH --cpus-per-task=14  # CPUs per task
#SBATCH --gpus-per-node=1   # GPUs per node
#SBATCH --time=12:00:00     # Time limit (adjust as needed)

# Load necessary modules (adjust based on your system)
module load cuda
module load conda

# Activate the Conda environment (adjust environment name as needed)
source activate cog_fl_llm_env

# Define parameter arrays

# Execute the script with the assigned parameters
LD_LIBRARY_PATH="" python3 test_generalization.py &
wait
