#!/bin/bash
#SBATCH -A cgb-l
#SBATCH --nodes=1
#SBATCH --ntasks=48
#SBATCH --cpus-per-task=1
#SBATCH --gpus-per-node=1
#SBATCH --time=96:00:00

# Some useful commands
# run the job:          sbatch run_experiments.sub
# check job status:     squeue -u $USERNAME ($USERNAME==apiasecz)
# check job details:    scontrol show job_id (job id from job status)
# interactive session:  sinteractive -A cgb-l -N1 -n32 --gpus-per-node=1 (this is for the H100, -A standby for A100, other options same as above)

# Variables
conda_env_used='cog_fl_llm_env'

# Load necessary packages
module load cuda
module load anaconda

# Activate desired environment
conda activate $conda_env_used

# Run the experiment code
# ./evaluate_policy.sh
python3 pretrain_models.py --seed 2
