#!/bin/bash
#SBATCH -A cgb              # Account name (adjust as needed)
#SBATCH -p ai               # Partition
#SBATCH -q preemptible           # Queue
#SBATCH --nodes=1           # Number of nodes
#SBATCH --ntasks=1          # Number of tasks
#SBATCH --cpus-per-task=14  # CPUs per task
#SBATCH --gpus-per-node=1   # GPUs per node
#SBATCH --time=12:00:00     # Time limit (adjust as needed)

# Load necessary modules (adjust based on your system)
module load cuda
module load conda

# Activate the Conda environment (adjust environment name as needed)
source activate cog_fl_llm_env

# Define parameter arrays

# Execute the script with the assigned parameters
python3 pretrain_models_MEMD-ABSA.py --seed 0 &
python3 pretrain_models_MEMD-ABSA.py --seed 1 &
python3 pretrain_models_MEMD-ABSA.py --seed 2 &

wait
